# Generated by Django 3.1.4 on 2020-12-22 09:59

from django.db import migrations, models
import dockertest.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20201222_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postimage',
            field=models.ImageField(blank=True, null=True, storage=dockertest.storage_backends.PrivateMediaStorage(), upload_to='myimage', verbose_name='첨부 이미지'),
        ),
    ]
