version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file:
      - .env
#    ports:
#      - "5432:5432"
  nginx:
    image: library/nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/code
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
#      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
  web:
#    build: .
    image: jwkcp/dockertest:latest
    volumes:
      - .:/code
#    ports:
#      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    entrypoint: ["/code/script/entrypoint_app.sh"]