version: "3.9"

services:
  nginx:
    image: library/nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
  web:
#    build: .
    image: jwkcp/dockertest:latest
    volumes:
      - .:/code
    env_file:
      - ./config/app/.env
#    entrypoint: ./entrypoint.sh